call plug#begin()
    Plug 'mhinz/vim-startify'
    Plug 'junegunn/goyo.vim'
call plug#end()

set belloff=all
set expandtab
set mouse=a
set nu
set shiftwidth=4
set smartindent
set tabstop=4

filetype indent on
syntax on

noremap <C-g> :Goyo<CR>
