let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
    Plug 'mhinz/vim-startify'
    Plug 'junegunn/goyo.vim'
call plug#end()

set belloff=all
set expandtab
set nu
set shiftwidth=4
set smartindent
set tabstop=4

filetype indent on
syntax on

noremap <C-g> :Goyo<CR>
