export EDITOR=vim
export LESSHISTFILE=/dev/null
export PURE_PROMPT_SYMBOL="[$((10#$(tty | sed 's/^[^0-9]*//')))] ❯"

alias ga='git add' gc='git commit -v' gl='git pull' gp='git push' gg='git gui' gst='git status'
alias y='xclip -selection clipboard' yi='y -t image/png -i' p='xclip -selection clipboard -o' 
alias ls='exa' l='exa -lbF --git' ll='exa -la --git' tree='exa --tree --git' ltree='tree -l'    
alias open='xdg-open' cat='bat' k='kubectl'

. /usr/local/Cellar/autojump/22.5.3_3/share/autojump/autojump.zsh
. /usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/handler.sh
. pack djui/alias-tips alias-tips.plugin.zsh:alias-tips.py master
. pack ohmyzsh/ohmyzsh lib/history.zsh master
# fzf key-bindings should be after omz
. pack ohmyzsh/ohmyzsh lib/key-bindings.zsh master
. pack junegunn/fzf shell/key-bindings.zsh master

setopt share_history

autoload -Uz compinit; compinit -C  # to apply new completion, run `compinit`
zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes

fpath+=($HOME/.local/share/zsh/pure)
autoload -U promptinit; promptinit
prompt pure
