export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="random"
ZSH_THEME_RANDOM_QUIET=true

plugins=(aws docker emotty fzf git z)

zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes
zstyle ':completion:*:*:-command-:*:*' ignored-patterns '_*'       

source $ZSH/oh-my-zsh.sh

setopt share_history
setopt no_nomatch
unsetopt beep

alias "open=xdg-open"
alias "y=xclip -selection clipboard"
alias "p=xclip -selection clipboard -o"
alias "trash-put=gio trash"
alias "trash-list=gio --list"

HISTSIZE=10000
SAVEHIST=1000000
EDITOR=vi
export LESSHISTFILE=/dev/null

PATH=$PATH:/usr/share/bcc/tools
