export EDITOR=nvim
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

alias ga='git add' gc='git commit -v' gl='git pull' gp='git push' gg='lazygit' gst='git status' gco='git checkout'
alias gr='git restore' grs='git restore --staged' gd='git diff' gds='git diff --staged' 
alias vi='nvim' vim='vi'
alias cat='bat' ls='eza' sl='ls' l='ls -l' ll='ls -al'
alias y='pbcopy' p='pbpaste'

autoload -U edit-command-line 
zle -N edit-command-line
bindkey '\C-x\C-e' edit-command-line
bindkey  '^[[1;2D'   beginning-of-line
bindkey  '^[[H'   beginning-of-line
bindkey  '^[[1;2C'   end-of-line
bindkey  '^[[F'   end-of-line

autoload -Uz compinit; compinit -C
eval "$(fzf --zsh)"
. /opt/homebrew/etc/profile.d/autojump.sh

fpath+=('/opt/homebrew/share/zsh/site-functions')

autoload -U promptinit; promptinit
prompt pure
