if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

export PATH=$PATH:$HOME/.local/bin
exec /usr/bin/i3
exec vmware-user-suid-wrapper
