for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
  [ -x "$f" ] && . "$f"
done
unset f

export GTK_IM_MODULE=uim
export QT_IM_MODULE=uim
uim-xim &
export XMODIFIERS=@im=uim

export PATH=$PATH:$HOME/.local/bin
exec i3 &>> /var/log/.i3.log
