export AUTOENV_ENABLE_LEAVE=1
export EDITOR=vim
export LESSHISTFILE=$HOME/.logs/less
export NODE_REPL_HISTORY=$HOME/.logs/node_repl
export PATH=$PATH:$HOME/.local/bin
export PURE_PROMPT_SYMBOL="$(echo ${${(%):-%l}##pts/} / 2 | bc) ❯"
export PYTHONSTARTUP=$HOME/.config/python/startup.py
export WGETRC=$HOME/.config/wget/wgetrc
export HISTFILE=$HOME/.logs/zsh

alias ga='git add' gc='git commit -v' gl='git pull' gp='git push' gg='git gui' gst='git status' gd='git diff' gds='git diff --staged' gco='git checkout'
alias ls='exa' l='exa -lbF --git' ll='exa -la --git' tree='exa --tree --git' ltree='tree -l'    
alias open='xdg-open' cat='bat'
alias tf='terraform' tfp='tf plan' tfa='tf apply' tfi='tf init'
alias y='xclip -selection clipboard' yi='y -t image/png -i' p='xclip -selection clipboard -o' 
alias rm="echo 'you should use \`trash\`'; false" t='trash'

. /usr/share/autojump/autojump.zsh
. /usr/share/doc/pkgfile/command-not-found.zsh
. pack djui/alias-tips alias-tips.plugin.zsh:alias-tips.py master
. pack ohmyzsh/ohmyzsh lib/history.zsh master
. pack hyperupcall/autoenv activate.sh master
# fzf key-bindings should be after omz
. pack ohmyzsh/ohmyzsh lib/key-bindings.zsh master
. pack junegunn/fzf shell/key-bindings.zsh master

setopt auto_pushd
setopt extended_glob
setopt interactive_comments
setopt share_history

autoload -Uz compinit; compinit -C  # to apply new completion, run `compinit`

change_ps() { export PURE_PROMPT_SYMBOL="$1 ❯"; }
tmp() { TMP=~/tmp/$(date +%F); mkdir -p $TMP; cd $TMP }

fpath+=($HOME/.local/share/zsh/pure)
autoload -U promptinit; promptinit
prompt pure
