export AUTOENV_ENABLE_LEAVE=1
export EDITOR=nvim
export HISTFILE=$HOME/.logs/zsh
export LESSHISTFILE=$HOME/.logs/less
export PATH=$PATH:$HOME/.local/bin:$HOME/go/bin
export PURE_PROMPT_SYMBOL="$(echo ${${(%):-%l}##pts/} / 2 | bc) ❯"
export PYTHONSTARTUP=$HOME/.config/python/startup.py
export WGETRC=$HOME/.config/wget/wgetrc

alias ga='git add' gc='git commit -v' gl='git pull' gp='git push' gg='lazygit' gst='git status' gco='git checkout'
alias gr='git restore' grs='git restore --staged' gd='git diff' gds='git diff --staged' 
alias ls='eza' l='eza -lbF --git' ll='eza -la --git' tree='eza --tree --git' ltree='tree -l'    
alias open='xdg-open' cat='bat'
alias tf='terraform' tfp='tf plan' tfa='tf apply' tfi='tf init'
alias y='xclip -selection clipboard' yi='y -t image/png -i' p='xclip -selection clipboard -o' 
alias rm="trash"
alias vi="nvim" vim="vi"

autoload -Uz compinit; compinit -C  # to apply new completion, run `compinit`

. /usr/share/autojump/autojump.zsh
. pack ohmyzsh/ohmyzsh plugins/command-not-found/command-not-found.plugin.zsh 
. pack djui/alias-tips alias-tips.plugin.zsh:alias-tips.py master
. pack ohmyzsh/ohmyzsh lib/history.zsh master
. pack hyperupcall/autoenv activate.sh master
# fzf key-bindings should be after omz
. pack ohmyzsh/ohmyzsh lib/key-bindings.zsh master
. pack junegunn/fzf shell/key-bindings.zsh master
. `which aws_zsh_completer.sh`

setopt auto_pushd
setopt extended_glob
setopt interactive_comments
setopt share_history


change_ps() { export PURE_PROMPT_SYMBOL="$1 ❯"; }
tmp() { TMP=~/tmp/$(date +%F); mkdir -p $TMP; cd $TMP }
function yy() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		cd -- "$cwd"
	fi
	rm -f -- "$tmp"
	zle accept-line
}
zle -N yy
bindkey '^E' yy

fpath+=($HOME/.local/share/zsh/pure)
autoload -U promptinit; promptinit
prompt pure
