for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
  [ -x "$f" ] && . "$f"
done
unset f

export GTK_IM_MODULE="fcitx5"
export QT_IM_MODULE="fcitx5"
export XMODIFIERS="@im=fcitx5"
fcitx5 &

setxkbmap -option "caps:none"
xmodmap ~/.Xmodmap

export PATH=$PATH:$HOME/projects/scripts/scripts
exec i3
