call plug#begin()
Plug 'junegunn/goyo.vim'
Plug 'mhinz/vim-startify'
call plug#end()

set autoindent
set backspace=indent,eol,start
set belloff=all
set expandtab
set mmp=8192
set nu
set shiftwidth=4
set tabstop=4
filetype plugin indent on

set termguicolors

noremap <C-g> :Goyo<CR>
