views:
  v1/pods:
    columns:
      - NAMESPACE
      - NAME
      - READY
      - STATUS
      - RESTARTS
      - AGE
      - IP
      - NODE
      - CPU
      - "%CPU/R"
      - "%CPU/L"
      - MEM
      - "%MEM/R"
      - "%MEM/L"
      - "PF|H"
  v1/nodes:
    columns:
      - "INTERNAL-IP|S"
      - "GPU/A|H"
      - "GPU/C|H"
      - "SH-GPU/A|H"
      - "SH-GPU/C|H"
