
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "dolphin"
local menu        = "hyprlauncher"

local scratchpadName      = "magic"
local scratchpadWorkspace = "special:" .. scratchpadName
local scratchpadTerminal  = "kitty --class scratchpad-terminal --config \"$HOME/.config/kitty/scratchpad.conf\""
local chromiumOverlayTag       = "super-grave-chromium"
local chromiumOverlayWorkspace = "special:super-grave-chromium"
local chromiumOverlayCommand   = "chromium --new-window 'chrome://newtab/'"
local chromiumOverlayFallbackWidth  = 779
local chromiumOverlayFallbackHeight = 351
local opacityControl      = "bash \"$HOME/.config/hypr/adjust-window-opacity.sh\""
local sessionGuard       = "\"$HOME/.local/libexec/sunglass\""
local sessionGuardSubmap = "session-guard"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function ()
    hl.exec_cmd("fcitx5 -d")
    hl.exec_cmd("waybar")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    -- A BlueZ Trusted flag is the allowlist: only explicitly trusted Bluetooth
    -- audio devices become the default output when they connect.
    hl.exec_cmd("bash \"$HOME/.config/hypr/bluetooth-audio-autoswitch.sh\"")
    -- Advertise an assistive-technology consumer so GTK/Qt apps publish their
    -- AT-SPI trees; wl-wysiwyc reads those to label clickable elements.
    -- Chromium ignores this signal and needs --force-renderer-accessibility
    -- instead (managed in chromium.tf via chromium-flags.conf).
    hl.exec_cmd("gsettings set org.gnome.desktop.interface toolkit-accessibility true")
    hl.exec_cmd("gsettings set org.gnome.desktop.a11y.applications screen-reader-enabled true")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XMODIFIERS", "@im=fcitx")
hl.env("QT_IM_MODULE", "fcitx")
hl.env("GTK_IM_MODULE", "fcitx")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 0,
        gaps_out = 0,

        border_size = 1,

        col = {
            active_border   = { colors = {"rgba(33ccffff)", "rgba(00ff99ff)"}, angle = 45 },
            inactive_border = "rgba(44444488)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 0,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,
        dim_special      = 0.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsMove",   enabled = false })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split    = true, -- You probably want this
        precise_mouse_move = true, -- Drop dragged windows on the cursor-facing side
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

-- Groupbar (tab bar) appearance. See https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    group = {
        groupbar = {
            font_size = 10, -- default 8, +25% so tab titles are legible
        },
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        disable_hyprland_logo   = true,
        disable_splash_rendering = true
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- SUPER belongs to the compositor, never to the focused app. A lone SUPER tap is
-- not part of any bind, so Hyprland would forward it to the client -- inside
-- virt-manager's SPICE console that reaches the Windows guest and pops the Start
-- menu. Claiming the bare keysym makes Hyprland swallow it instead.
--
-- The empty modmask is deliberate: Hyprland emits the key event before xkb folds
-- the press into the modifier state, so a lone SUPER press is still seen as "no
-- modifiers held". Suppressing the press also suppresses its release, so no
-- stray key-up escapes either. SUPER as a modifier is unaffected -- clients keep
-- receiving wl_keyboard.modifiers, and SUPER + <key> binds read the xkb state
-- rather than this event.
--
-- No description on purpose: this is not a user-facing shortcut, and
-- show-keybinds.sh lists only binds that carry one.
hl.bind("Super_L", function() end)

-- Keep shortcut descriptions next to the actual bindings. show-keybinds.sh
-- reads them back from `hyprctl binds`, so the overlay cannot silently drift
-- away from this config.
local function bind(keys, dispatcher, description, options)
    options = options or {}
    options.description = description
    return hl.bind(keys, dispatcher, options)
end

-- Pinning only works for floating windows. Remember which windows this shortcut
-- floated itself so a second press can restore those windows to tiling. Windows
-- that were already floating remain floating when they are unpinned.
local stickyAutoFloated = {}
local function toggleStickyWindow()
    local w = hl.get_active_window()
    if not w then return end

    local id = tostring(w.stable_id)
    if w.pinned then
        hl.dispatch(hl.dsp.window.pin({ action = "unset", window = w }))
        if stickyAutoFloated[id] then
            hl.dispatch(hl.dsp.window.float({ action = "unset", window = w }))
        end
        stickyAutoFloated[id] = nil
        return
    end

    -- Hyprland cannot pin a fullscreen window. Leave it unchanged rather than
    -- unexpectedly taking it out of fullscreen.
    if w.fullscreen ~= 0 then return end

    stickyAutoFloated[id] = not w.floating
    if not w.floating then
        hl.dispatch(hl.dsp.window.float({ action = "set", window = w }))
    end
    hl.dispatch(hl.dsp.window.pin({ action = "set", window = w }))
end

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
local function openTerminal()
    local special = hl.get_active_special_workspace()
    local command = special and special.name == scratchpadWorkspace
        and scratchpadTerminal
        or terminal
    hl.exec_cmd(command)
end

bind(mainMod .. " + return", openTerminal, "앱 · 터미널 열기")
local closeWindowBind = bind(mainMod .. " + Q", hl.dsp.window.close(), "창 · 닫기")
-- closeWindowBind:set_enabled(false)
bind(mainMod .. " + M", hl.dsp.exit(), "세션 · 종료")
bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager), "앱 · 파일 관리자 열기")
bind(mainMod .. " + T", hl.dsp.window.float({ action = "toggle" }), "창 · 타일/플로팅 전환")
bind(mainMod .. " + SHIFT + T", toggleStickyWindow, "창 · 모든 워크스페이스에 고정/해제")
bind(mainMod .. " + Prior", hl.dsp.exec_cmd(opacityControl .. " increase"), "창 · 불투명도 20% 높이기")
bind(mainMod .. " + Next",  hl.dsp.exec_cmd(opacityControl .. " decrease"), "창 · 불투명도 20% 낮추기")
bind(mainMod .. " + D", hl.dsp.exec_cmd(menu), "앱 · 런처 열기")
bind(mainMod .. " + H", hl.dsp.exec_cmd("bash \"$HOME/.config/hypr/show-keybinds.sh\""), "도움말 · 단축키 목록 열기/닫기")
-- Fake fullscreen (SUPER+F): tell the focused app it is fullscreen (client = 2)
-- while keeping the window's real tiled geometry (internal = 0), then toggle back
-- off. Hyprland 0.55 removed the old `fakefullscreen` dispatcher; this drives its
-- replacement, `fullscreenstate`, via hl.dsp.window.fullscreen_state.
local function toggleFakeFullscreen(w)
    w = w or hl.get_active_window()
    if not w then return end
    local client = (w.fullscreen_client == 2) and 0 or 2
    hl.dispatch(hl.dsp.window.fullscreen_state({
        internal = 0,
        client   = client,
        window   = w,
    }))
end
bind(mainMod .. " + F", toggleFakeFullscreen, "창 · 앱 UI만 전체화면 전환")
-- Real fullscreen (SUPER+SHIFT+F): actually fill the monitor (internal = 2) and
-- tell the app too (client = 2), then toggle back off. Same fullscreenstate
-- mechanism as the fake bind above, but it changes the window geometry as well.
bind(mainMod .. " + SHIFT + F", function()
    local w = hl.get_active_window()
    if not w then return end
    local state = (w.fullscreen == 2) and 0 or 2
    hl.dispatch(hl.dsp.window.fullscreen_state({ internal = state, client = state }))
end, "창 · 실제 전체화면 전환")
bind(mainMod .. " + J", hl.dsp.layout("togglesplit"), "배치 · 현재 split 가로/세로 전환") -- dwindle only

-- macOS-style shortcuts: translate SUPER + <key> into its Linux equivalent and
-- send that to the focused window. Omitting the `window` field from send_key_state
-- targets the active window. Copy/paste map to Ctrl/Shift+Insert so they work in both
-- terminals (kitty) and GUI apps. Send an explicit down/up pair instead of a
-- stateful send_shortcut, whose synthetic key-up can be lost during fast modifier
-- rollover (for example SUPER+V followed immediately by Shift).
local function sendKeyTap(mods, key)
    return function()
        hl.dispatch(hl.dsp.send_key_state({ mods = mods, key = key, state = "down" }))
        hl.dispatch(hl.dsp.send_key_state({ mods = mods, key = key, state = "up" }))
    end
end

for _, sc in ipairs({
    { on = "C", mods = "CTRL",  send = "Insert", description = "편집 · 복사" }, -- copy
    { on = "V", mods = "SHIFT", send = "Insert", description = "편집 · 붙여넣기" }, -- paste
    { on = "X", mods = "CTRL",  send = "X",      description = "편집 · 잘라내기" },
    { on = "R", mods = "CTRL",  send = "R",      description = "편집 · 새로고침" },
    { on = "W", mods = "CTRL",  send = "W",      description = "편집 · 탭/문서 닫기" },
    { on = "A", mods = "CTRL",  send = "A",      description = "편집 · 전체 선택" },
    { on = "Z", mods = "CTRL",  send = "Z",      description = "편집 · 실행 취소" },
}) do
    bind(mainMod .. " + " .. sc.on, sendKeyTap(sc.mods, sc.send), sc.description)
end

-- Move focus with mainMod + arrow keys
bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }),  "포커스 · 왼쪽 창")
bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }), "포커스 · 오른쪽 창")
bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }),    "포커스 · 위쪽 창")
bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }),  "포커스 · 아래쪽 창")

-- Same focus moves without leaving the letter block: p [ ] form an inverted T
-- under `-`, mirroring the arrow cluster.
--
--        -            (up)
--    p   [   ]        (left / down / right)
--
-- `-` sits directly above `[` on a US layout, so the shape matches the arrows.
-- P used to toggle pseudotile; that bind is gone in favour of this one.
bind(mainMod .. " + P",            hl.dsp.focus({ direction = "left" }),  "포커스 · 왼쪽 창")
bind(mainMod .. " + bracketright", hl.dsp.focus({ direction = "right" }), "포커스 · 오른쪽 창")
bind(mainMod .. " + minus",        hl.dsp.focus({ direction = "up" }),    "포커스 · 위쪽 창")
bind(mainMod .. " + bracketleft",  hl.dsp.focus({ direction = "down" }),  "포커스 · 아래쪽 창")

bind(mainMod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "left" }),  "배치 · 창을 왼쪽으로 이동")
bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }), "배치 · 창을 오른쪽으로 이동")
bind(mainMod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "up" }),    "배치 · 창을 위쪽으로 이동")
bind(mainMod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "down" }),  "배치 · 창을 아래쪽으로 이동")

bind(mainMod .. " + CTRL + left",  hl.dsp.window.resize({ x = -20, y = 0, relative = true}), "크기 · 너비 줄이기", { repeating = true })
bind(mainMod .. " + CTRL + right", hl.dsp.window.resize({ x =  20, y = 0, relative = true}), "크기 · 너비 늘리기", { repeating = true })
bind(mainMod .. " + CTRL + up",    hl.dsp.window.resize({ x = 0, y = -20, relative = true}), "크기 · 높이 줄이기", { repeating = true })
bind(mainMod .. " + CTRL + down",  hl.dsp.window.resize({ x = 0, y =  20, relative = true}), "크기 · 높이 늘리기", { repeating = true })

-- Groups / tabbed windows. See https://wiki.hypr.land/Configuring/Basics/Dispatchers/#group
-- 현재 창으로 group/tab 만들기 또는 해제
bind(mainMod .. " + G", hl.dsp.group.toggle(), "그룹 · 탭 그룹 만들기/해제")

-- group 안에서 다음/이전 탭으로 이동
bind(mainMod .. " + TAB",         hl.dsp.group.next(), "그룹 · 다음 탭")
bind(mainMod .. " + SHIFT + TAB", hl.dsp.group.prev(), "그룹 · 이전 탭")

-- group 안에서 현재 창 순서 이동
bind(mainMod .. " + CTRL + TAB", hl.dsp.group.move_window({ forward = true }), "그룹 · 현재 탭을 뒤로 이동")

-- 현재 group 잠금: 새 창이 자동으로 group에 안 들어오게
bind(mainMod .. " + SHIFT + G", hl.dsp.group.lock(), "그룹 · 새 창 자동 합류 잠금")

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i}), "워크스페이스 · " .. i .. "번으로 이동")
    bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }), "워크스페이스 · 창을 " .. i .. "번으로 보내기")
end

-- A special workspace already follows workspace changes while it is visible,
-- so pinning its windows is neither necessary nor supported by Hyprland.
hl.config({
    binds = {
        hide_special_on_workspace_change = false,
    },
})

local function moveActiveWindowToScratchpad()
    local w = hl.get_active_window()
    if not w then return end

    -- A pinned window cannot be moved to a special workspace.
    if w.pinned then
        hl.dispatch(hl.dsp.window.pin({ action = "disable", window = w }))
    end
    stickyAutoFloated[tostring(w.stable_id)] = nil

    if w.fullscreen ~= 0 or w.fullscreen_client ~= 0 then
        hl.dispatch(hl.dsp.window.fullscreen_state({
            internal = 0,
            client   = 0,
            action   = "set",
            window   = w,
        }))
    end

    hl.dispatch(hl.dsp.window.move({ workspace = scratchpadWorkspace, window = w }))

    -- Scratchpad windows tile normally, so additional terminals split the
    -- workspace instead of appearing as independent floating windows.
    if w.floating then
        hl.dispatch(hl.dsp.window.float({ action = "disable", window = w }))
    end
end

local function findChromiumOverlay()
    return hl.get_windows({ tag = chromiumOverlayTag })[1]
end

-- Enable this rule only while launching the overlay. Chromium may hand a new
-- window to an already-running browser process, so exec PID rules are not
-- reliable here. A short-lived class rule keeps the new window out of the
-- tiling layout from its first map instead of floating it after the layout has
-- already been recalculated.
local chromiumOverlayLaunchRule = hl.window_rule({
    name             = "chromium-overlay-launch",
    enabled          = false,
    match            = { class = "chromium" },
    float            = true,
    center           = true,
    workspace        = chromiumOverlayWorkspace .. " silent",
    no_initial_focus = true,
})

local function setChromiumOverlayOpacity(w)
    for _, prop in ipairs({ "opacity", "opacity_inactive", "opacity_fullscreen" }) do
        hl.dispatch(hl.dsp.window.set_prop({ prop = prop, value = "0.60", window = w }))
    end
    for _, prop in ipairs({ "opacity_override", "opacity_inactive_override", "opacity_fullscreen_override" }) do
        hl.dispatch(hl.dsp.window.set_prop({ prop = prop, value = "true", window = w }))
    end
end

local function configureChromiumOverlay(w, width, height)
    -- The launch rule handles this before map in the normal case. Keep the
    -- dispatcher as a fallback for Chromium builds that change their initial
    -- class after window rules have run.
    if not w.floating then
        hl.dispatch(hl.dsp.window.float({ action = "set", window = w }))
    end

    -- Give Chromium its fullscreen UI without putting the compositor window
    -- into fullscreen. The compositor can therefore keep it floating/pinned.
    hl.dispatch(hl.dsp.window.fullscreen_state({
        internal = 0,
        client   = 2,
        action   = "set",
        window   = w,
    }))
    hl.dispatch(hl.dsp.window.resize({
        x      = width,
        y      = height,
        window = w,
    }))
    setChromiumOverlayOpacity(w)
end

local function showChromiumOverlay(w)
    local monitor = hl.get_active_monitor()
    local workspace = monitor and hl.get_active_workspace(monitor)
    if not monitor or not workspace then return end

    -- A pinned window cannot move between workspaces. Reattach it to the
    -- currently active workspace first, then restore the sticky state.
    if w.pinned then
        hl.dispatch(hl.dsp.window.pin({ action = "unset", window = w }))
    end
    if not w.floating then
        hl.dispatch(hl.dsp.window.float({ action = "set", window = w }))
    end
    hl.dispatch(hl.dsp.window.move({ workspace = workspace, follow = false, window = w }))
    hl.dispatch(hl.dsp.window.fullscreen_state({
        internal = 0,
        client   = 2,
        action   = "set",
        window   = w,
    }))
    hl.dispatch(hl.dsp.window.center({ window = w }))
    setChromiumOverlayOpacity(w)
    hl.dispatch(hl.dsp.window.pin({ action = "set", window = w }))
    hl.dispatch(hl.dsp.focus({ window = w }))
    hl.dispatch(hl.dsp.window.bring_to_top())
end

local function hideChromiumOverlay(w)
    if w.pinned then
        hl.dispatch(hl.dsp.window.pin({ action = "unset", window = w }))
    end
    if not w.floating then
        hl.dispatch(hl.dsp.window.float({ action = "set", window = w }))
    end
    hl.dispatch(hl.dsp.window.move({
        workspace = chromiumOverlayWorkspace,
        follow    = false,
        window    = w,
    }))
end

local chromiumOverlayLaunchTimer
local chromiumOverlayShouldShow = false

local function finishChromiumOverlayLaunch()
    chromiumOverlayLaunchRule:set_enabled(false)
    if chromiumOverlayLaunchTimer then
        chromiumOverlayLaunchTimer:set_enabled(false)
        chromiumOverlayLaunchTimer = nil
    end
end

local function launchChromiumOverlay()
    local sourceWindow = hl.get_active_window()
    local launchWidth = chromiumOverlayFallbackWidth
    local launchHeight = chromiumOverlayFallbackHeight
    if sourceWindow and sourceWindow.class == "kitty" then
        launchWidth = sourceWindow.size.x
        launchHeight = sourceWindow.size.y
    end

    local existingChromiumWindows = {}
    for _, w in ipairs(hl.get_windows({ class = "chromium" })) do
        existingChromiumWindows[tostring(w.stable_id)] = true
    end

    chromiumOverlayLaunchRule:set_enabled(true)
    local attempts = 0
    chromiumOverlayLaunchTimer = hl.timer(function()
        attempts = attempts + 1

        for _, w in ipairs(hl.get_windows({ class = "chromium" })) do
            if not existingChromiumWindows[tostring(w.stable_id)] then
                finishChromiumOverlayLaunch()
                hl.dispatch(hl.dsp.window.tag({ tag = "+" .. chromiumOverlayTag, window = w }))
                configureChromiumOverlay(w, launchWidth, launchHeight)

                if chromiumOverlayShouldShow then
                    showChromiumOverlay(w)
                else
                    hideChromiumOverlay(w)
                end
                return
            end
        end

        if attempts >= 100 then
            finishChromiumOverlayLaunch()
            chromiumOverlayShouldShow = false
        end
    end, { timeout = 50, type = "repeat" })

    hl.exec_cmd(chromiumOverlayCommand)
end

local function toggleChromiumOverlay()
    local w = findChromiumOverlay()
    if w then
        local shown = w.visible and w.workspace and w.workspace.name ~= chromiumOverlayWorkspace
        chromiumOverlayShouldShow = not shown
        if shown then
            hideChromiumOverlay(w)
        else
            showChromiumOverlay(w)
        end
        return
    end

    if chromiumOverlayLaunchTimer then
        chromiumOverlayShouldShow = not chromiumOverlayShouldShow
        return
    end

    chromiumOverlayShouldShow = true
    launchChromiumOverlay()
end

bind(mainMod .. " + grave",         toggleChromiumOverlay,        "앱 · 반투명 Chromium 열기/숨기기")
bind(mainMod .. " + SHIFT + grave", moveActiveWindowToScratchpad, "워크스페이스 · 창을 scratchpad로 보내기")

-- Scroll through existing workspaces with mainMod + scroll
bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), "워크스페이스 · 다음으로 이동")
bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }), "워크스페이스 · 이전으로 이동")

-- Reuse the middle button as a context-sensitive gesture. Floating windows
-- move exactly like SUPER+LMB. On tiled windows, directional drags of at least
-- 80 logical pixels navigate tabs (left/right), restore a closed tab (up), or
-- close the current tab (down). One short click remains Ctrl+LMB; two short
-- clicks on the same tiled window toggle fake fullscreen like SUPER+F.
local middleSwipeDistance = 80
local middleClickMoveTolerance = 8
local middleDoubleClickTimeout = 400
local dragFloatingWindow = hl.dsp.window.drag()
local floatingMiddleDragActive = false
local tiledMiddleGesture
local pendingTiledMiddleClick
local pendingTiledMiddleClickTimer

local function sendSyntheticTap(mods, key, window)
    for _, state in ipairs({ "down", "up" }) do
        hl.dispatch(hl.dsp.send_key_state({
            mods   = mods,
            key    = key,
            state  = state,
            window = window,
        }))
    end
end

local function sendPendingTiledMiddleClick()
    local click = pendingTiledMiddleClick
    pendingTiledMiddleClick = nil
    pendingTiledMiddleClickTimer = nil
    if click then
        sendSyntheticTap("CTRL", "mouse:272", click.window)
    end
end

local function handleTiledMiddleClick(gesture)
    local pending = pendingTiledMiddleClick
    if pending and tostring(pending.window.stable_id) == tostring(gesture.window.stable_id) then
        pendingTiledMiddleClickTimer:set_enabled(false)
        pendingTiledMiddleClick = nil
        pendingTiledMiddleClickTimer = nil
        toggleFakeFullscreen(gesture.window)
        return
    end

    if pending then
        pendingTiledMiddleClickTimer:set_enabled(false)
        sendPendingTiledMiddleClick()
    end

    pendingTiledMiddleClick = gesture
    pendingTiledMiddleClickTimer = hl.timer(sendPendingTiledMiddleClick, {
        timeout = middleDoubleClickTimeout,
        type    = "oneshot",
    })
end

-- The floating dispatcher asks Hyprland to call this bind again on release so
-- it can end the compositor-owned window drag. Tiled releases are handled by
-- the separate release bind below.
local function handleMiddlePressOrFloatingRelease()
    if floatingMiddleDragActive then
        hl.dispatch(dragFloatingWindow)
        floatingMiddleDragActive = false
        return
    end

    local w = hl.get_active_window()
    if not w then return end

    if w.floating then
        floatingMiddleDragActive = true
        hl.dispatch(dragFloatingWindow)
        return
    end

    local cursor = hl.get_cursor_pos()
    if not cursor then return end
    tiledMiddleGesture = {
        window = w,
        x      = cursor.x,
        y      = cursor.y,
    }
end

local function finishTiledMiddleGesture()
    local gesture = tiledMiddleGesture
    tiledMiddleGesture = nil
    if not gesture then return end

    local cursor = hl.get_cursor_pos()
    if not cursor then return end

    local dx = cursor.x - gesture.x
    local dy = cursor.y - gesture.y
    local absDx = math.abs(dx)
    local absDy = math.abs(dy)
    if absDx <= middleClickMoveTolerance and absDy <= middleClickMoveTolerance then
        handleTiledMiddleClick(gesture)
    elseif math.max(absDx, absDy) < middleSwipeDistance then
        sendSyntheticTap("CTRL", "mouse:272", gesture.window)
    elseif absDx > absDy then
        if dx < 0 then
            sendSyntheticTap("CTRL + SHIFT", "Tab", gesture.window)
        else
            sendSyntheticTap("CTRL", "Tab", gesture.window)
        end
    elseif dy < 0 then
        sendSyntheticTap("CTRL + SHIFT", "T", gesture.window)
    else
        sendSyntheticTap("CTRL", "W", gesture.window)
    end
end

bind("mouse:274", handleMiddlePressOrFloatingRelease, "마우스 · 플로팅 창 이동/타일 창 Ctrl+클릭·탭 제스처·더블클릭 전체화면")
hl.bind("mouse:274", finishTiledMiddleGesture, { release = true })

-- Move/resize windows with mainMod + LMB/RMB and dragging
bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   "마우스 · 창 이동", { mouse = true })
bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), "마우스 · 창 크기 조절", { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), "미디어 · 음량 높이기", { locked = true, repeating = true })
bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      "미디어 · 음량 낮추기", { locked = true, repeating = true })
bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     "미디어 · 음소거 전환", { locked = true, repeating = true })
bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   "미디어 · 마이크 음소거 전환", { locked = true, repeating = true })
bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  "화면 · 밝기 높이기", { locked = true, repeating = true })
bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  "화면 · 밝기 낮추기", { locked = true, repeating = true })

-- Requires playerctl
bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       "미디어 · 다음 트랙", { locked = true })
bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), "미디어 · 재생/일시정지", { locked = true })
bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), "미디어 · 재생/일시정지", { locked = true })
bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   "미디어 · 이전 트랙", { locked = true })

-- Physical keypad keycodes keep these controls stable regardless of Num Lock:
-- KP4/KP5/KP6 are previous/play-pause/next, KP8/KP2 adjust the volume,
-- and KP0 (KP_Insert with Num Lock off) toggles mute.
bind("code:83", hl.dsp.exec_cmd("playerctl previous"),                                      "미디어 · 숫자패드 4로 이전 트랙", { locked = true })
bind("code:84", hl.dsp.exec_cmd("playerctl play-pause"),                                    "미디어 · 숫자패드 5로 재생/일시정지", { locked = true })
bind("code:85", hl.dsp.exec_cmd("playerctl next"),                                          "미디어 · 숫자패드 6으로 다음 트랙", { locked = true })
bind("code:80", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),           "미디어 · 숫자패드 8로 음량 높이기", { locked = true, repeating = true })
bind("code:88", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),                "미디어 · 숫자패드 2로 음량 낮추기", { locked = true, repeating = true })
bind("code:90", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),               "미디어 · 숫자패드 0으로 음소거 전환", { locked = true })

-- Screenshots: hyprshot captures (region/window/full output) and pipes the raw
-- image to satty for annotation. Escape copies the current result (including any
-- annotations) to the clipboard and closes Satty.
-- CTRL+Print captures the focused window immediately, without asking for a window
-- selection. SHIFT+Print toggles a selected-region recording, while
-- CTRL+SHIFT+Print toggles a recording cropped to the focused window. ALT+Print
-- selects a region and stitches it into a long image while that region is scrolled.
local satty = "satty -f - --copy-command wl-copy --actions-on-escape=save-to-clipboard,exit --early-exit"
-- Keep capture shortcuts available inside temporary input modes such as
-- wl-wysiwyc's keyboard-navigation submap.
local captureBinds = {}
local function captureBind(keys, dispatcher, description)
    captureBinds[#captureBinds + 1] = bind(keys, dispatcher, description, { submap_universal = true })
end
captureBind("Print",                       hl.dsp.exec_cmd("hyprshot -m region --freeze --raw | " .. satty), "캡처 · 선택 영역 스크린샷 후 주석")
captureBind(mainMod .. " + Print",         hl.dsp.exec_cmd("hyprshot -m window --raw | " .. satty),          "캡처 · 선택한 창 스크린샷 후 주석")
captureBind(mainMod .. " + SHIFT + Print", hl.dsp.exec_cmd("hyprshot -m output --raw | " .. satty),          "캡처 · 모니터 스크린샷 후 주석")
captureBind("ALT + Print",                 hl.dsp.exec_cmd("wayscrollshot"),                                  "캡처 · 스크롤 영역을 긴 이미지로 저장")
captureBind("SHIFT + Print",               hl.dsp.exec_cmd("bash \"$HOME/.config/hypr/record-region.sh\""),   "녹화 · 선택 영역 시작/중지")
captureBind("CTRL + Print",                hl.dsp.exec_cmd("hyprshot -m window -m active --raw | " .. satty), "캡처 · 현재 창 즉시 스크린샷 후 주석")
captureBind("CTRL + SHIFT + Print",        hl.dsp.exec_cmd("bash \"$HOME/.config/hypr/record-region.sh\" toggle-window"), "녹화 · 현재 창 시작/중지")

-- Universal capture shortcuts must not bypass the private session guard.
local function updateCaptureBinds(submap)
    local enabled = submap ~= sessionGuardSubmap
    for _, capture in ipairs(captureBinds) do
        capture:set_enabled(enabled)
    end
end
updateCaptureBinds(hl.get_current_submap())
hl.on("keybinds.submap", updateCaptureBinds)

-- Keyboard-driven clicking: the Hangul key opens wl-wysiwyc, which labels the
-- focused window's clickable elements; typing a label puts the pointer on it,
-- then - clicks and = right-clicks. IME toggling lives on Launch8 (keyd maps
-- capslock to f17), so this key is free. The tool cancels a running overlay
-- when it is launched again, which makes this key a toggle.
bind("Hangul", hl.dsp.exec_cmd("\"$HOME/projects/wl-wysiwyc/target/release/wl-wysiwyc\""), "마우스 · 키보드로 클릭 (wl-wysiwyc)")


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

hl.window_rule({
    name  = "style-scratchpad",
    match = { workspace = scratchpadWorkspace },

    -- Keep the regular workspace behind the scratchpad sharp and visible.
    no_blur = true,
    opacity = "0.90 override 0.82 override 0.90 override",
})

hl.window_rule({
    name  = "style-scratchpad-terminal",
    match = {
        workspace = scratchpadWorkspace,
        class     = "^scratchpad-terminal$",
    },

    -- Kitty makes only its background translucent, keeping text fully opaque.
    opacity = "1.0 override 1.0 override 1.0 override",
})

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- virt-manager's SPICE console grabs the keyboard through GTK, which on Wayland
-- means zwp_keyboard_shortcuts_inhibit. While that inhibitor is up Hyprland stops
-- handling *every* keybind and hands the raw keys to the guest, so SUPER + <key>
-- lands in Windows instead of here. The Windows guest has no use for them, so
-- refuse the inhibitor for this window and keep SUPER host-side. Combined with the
-- bare Super_L bind above, the guest never sees the key at all.
hl.window_rule({
    name  = "vm-console-keeps-host-shortcuts",
    match = { class = "^virt-manager$" },

    no_shortcuts_inhibit = true,
})

-- Keep the CertMind phone emulator available without reflowing tiled windows.
-- The size follows the monitor height, while the phone stays tucked against the
-- right edge and pinned across workspaces. Match the main AVD window only; the
-- narrow Emulator toolbar remains an ordinary companion window.
hl.window_rule({
    name = "certmind-emulator-sticky",
    match = {
        class = "^Emulator$",
        title = "^Android Emulator - certmind_api_36:[0-9]+$",
    },

    float = true,
    pin   = true,
    size  = "620 monitor_h-80",
    move  = "monitor_w-w-40 40",
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

local suspendAfterLock = "sh -c '" .. sessionGuard .. " lock; sleep 1; systemctl suspend'"

-- The private guard owns all input decisions; the compositor only isolates its
-- session and preserves explicit hard-lock shortcuts.
hl.define_submap(sessionGuardSubmap, function()
    hl.bind("SUPER + CTRL + L", hl.dsp.exec_cmd(sessionGuard .. " lock"))
    hl.bind("SUPER + SHIFT + L", hl.dsp.exec_cmd(suspendAfterLock))
    hl.bind("SUPER + L", function() end)
    hl.bind("catchall", function() end, { ignore_mods = true, non_consuming = true })
end)

bind("SUPER + L", function()
    hl.dispatch(hl.dsp.submap(sessionGuardSubmap))
    hl.exec_cmd(sessionGuard .. " activate")
end, "세션 · 보호 모드")
bind("SUPER + CTRL + L", hl.dsp.exec_cmd(sessionGuard .. " lock"), "세션 · 화면 잠그기")
bind("SUPER + SHIFT + L", hl.dsp.exec_cmd(suspendAfterLock), "세션 · 잠근 뒤 절전")
