--local arrangeDesktop = hs.loadSpoon('ArrangeDesktop')
--arrangeDesktop:addMenuItems()
--
--hs.hotkey.bind({'command'}, 'f3', function()
--    arrangeDesktop:createArrangement()
--end)
--
--hs.hotkey.bind({}, 'f3', function()
--    arrangeDesktop:arrange('two-monitors')
--    hs.alert.show('Arranged desktop for three-monitors')
--end)
