#!/bin/bash

ln -sh $(realpath gitconfig) ~/.gitconfig
ln -sh $(realpath hammerspoon) ~/.hammerspoon
ln -sh $(realpath zshrc) ~/.zshrc
ln -sh $(realpath nvim) ~/.config/nvim
ln -sh $(realpath starship.toml) ~/.config/starship.toml
