export EDITOR=nvim
export FZF_CTRL_R_OPTS="--scheme=history"
export LESSHISTFILE=/dev/null
export WORDCHARS=""
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export HISTFILE="$HOME/projects/shell-history/mac-mini-m2-pro"
export HISTSIZE=1000000000
export SAVEHIST=1000000000

alias c='IS_DEMO=1 claude --dangerously-skip-permissions --ide --chrome'
alias o='codex --dangerously-bypass-approvals-and-sandbox'
alias ga='git add' gc='git commit -v' gl='git pull' gp='git push' gg='lazygit' gst='git status' gco='git checkout'
alias gr='git restore' grs='git restore --staged' gd='git diff' gds='git diff --staged' glog='git log --all --decorate --oneline --graph'
alias ls='eza' l='eza -lbF --git' ll='eza -la --git' tree='eza --tree --git' ltree='tree -l'    
alias cat='bat'
alias vi="nvim" vim="vi"
alias y='pbcopy' p='pbpaste'
alias rr='source ~/.zshrc'
alias rm='echo "rm is disabled. use \`trash\` command instead."'
alias -g ...='../..'
alias -g ....='../../..'

setopt append_history
setopt autopushd
setopt extended_glob
setopt hist_find_no_dups
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_reduce_blanks
setopt hist_save_no_dups
setopt inc_append_history
setopt interactive_comments
setopt share_history

bindkey -e
bindkey '^[[1;3C' forward-word
bindkey '^[[1;3D' backward-word
bindkey '^[[1;5C' end-of-line
bindkey '^[[1;5D' beginning-of-line
bindkey '^[b' beginning-of-line
bindkey '^[f' end-of-line

source <(fzf --zsh)
source ~/.zsh/alias-tips/alias-tips.plugin.zsh

tmp() { 
    TMP=~/tmp/$(date +%F)
    if [ "$#" -gt 0 ]; then
        TMP="${TMP}-$(echo "$@" | tr ' ' '-')"
    fi
    mkdir -p "$TMP"
    cd "$TMP"
}

eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
